### ISSUE TITLE
Test Ressource Upload

### ISSUE THREAD

**Issue by myamy** [ASKnetCommunity/ASKnet.Community#78]
### Title

Media Hub Business Model Canvas

### Sub-Title

A Business Model Canvas is a structured summary of the most important aspects of any business: Which problem does the business solve for whom by doing what - and how does it generate revenue? The canvas is a representation of the business model and as such gives hub teams the opportunity to co-create and over time further adapt their media hub's business model.

### Picture

![Media Hub Business Model - Media Hub Business Model Canvas](https://user-images.githubusercontent.com/4108917/148500074-0828e7ff-57f6-47b0-bd7f-232ea9be86e4.jpg)

### Reference Link

https://miro.com/app/board/uXjVOXFWNYQ=/?invite_link_id=648015904412

**Comment by myamy** [comment]
Does this work? What is missing / needed beyond the fields to make it a usable ressource?

**Comment by MartinSchott** [comment]
@myamy 
it looks like that now: 
![grafik](https://user-images.githubusercontent.com/8080649/153417719-7935a277-45e5-41e5-ba26-813ed6885e3b.png)


1. unfortunately the subtitle was far too long for the layout of the website. I shortened it to:   (hope it's okay)

> Craft the business model of your hub

2. for a resource in the training configurator a few more properties are needed. If you have the time, can you complete duration, difficulty, cost, license? Then I would create your resource in the configurator as well. 

```yaml
    name: 'Media Hub Business Model Canvas'
    id: 'hub-canvas'     #just internal use 
    url: 'https://miro.com/app/board/uXjVOXFWNYQ=/?invite_link_id=648015904412'
    duration: 0     #in minutes
    difficulty:     #1-3, 1 is easyest
    cost: 10      #in $
    license: 
```
